### PR TITLE
Update CI/tests to allow running proper, realistic unit tests

### PR DESCRIPTION
**Pull request by andersy005**
This PR is one step towards a more robust CI system. I modified a few methods but kept the functionality the same. I intend to look into a refactor of the `RemoteRunner` so as to facilitate testing it in a separate PR. 

- [x] Create SSH Key for localhost
- [x] Add tests
- [x] Rewrite some methods to allow easy testing.
- [x] Towards #135

### CODE REVIEW

**Review by mnlevy1981 — CHANGES_REQUESTED** [review]
The code you've included looks good, but I think we should modify `.github/workflows/ci.yaml` to test with `sh` and `tcsh` in addition to `bash`. I think, as written, we should get passes from `sh` but `test_run_command` will fail on `tcsh`. I'm okay with accepting this PR with a failing test in that case, I just want the test in place before we start refactoring to make it easier to support multiple shell options.

**Comment by andersy005** [comment]
>  I think we should modify .github/workflows/ci.yaml to test with sh and tcsh in addition to bash

I intend to address this within pytest unit tests instead of controlling this parametrization at the CI level. I avoided doing this in this PR since it would have required re-writing some parts of the code base and I wanted to make sure the SSH setup is working before breaking the tests...

**Review by mnlevy1981 — APPROVED** [review]
Makes sense! Sorry if we talked about this earlier and I just misunderstood what the intended plan was :)

**Comment by andersy005** [comment]
No worries... You are right. During our last conversation, we had talked about parameterizing shells at the CI level. However, I think parametrizing this in the unit tests gives us more flexibility/control.

**Pull request merged**
